-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SAFE_GATE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAFE_GATE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAFE_GATE` DEFAULT CHARACTER SET utf8 ;
USE `SAFE_GATE` ;

-- -----------------------------------------------------
-- Table `SAFE_GATE`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`FUNCIONARIO` (
  `ID_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `FUNCAO` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_FUNCIONARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`QUADRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`QUADRA` (
  `ID_QUADRA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_QUADRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`BLOCO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`BLOCO` (
  `ID_BLOCO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `ID_QUADRA` INT NOT NULL,
  PRIMARY KEY (`ID_BLOCO`),
  INDEX `fk_Bloco_Quadra_idx` (`ID_QUADRA` ASC),
  CONSTRAINT `fk_Bloco_Quadra`
    FOREIGN KEY (`ID_QUADRA`)
    REFERENCES `SAFE_GATE`.`QUADRA` (`ID_QUADRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`PROPRIETARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`PROPRIETARIO` (
  `ID_PROPRIETARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PROPRIETARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`APARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`APARTAMENTO` (
  `ID_APARTAMENTO` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL,
  `ID_BLOCO` INT NOT NULL,
  `ID_PROPRIETARIO` INT NOT NULL,
  PRIMARY KEY (`ID_APARTAMENTO`),
  INDEX `fk_Apartamento_Bloco1_idx` (`ID_BLOCO` ASC),
  INDEX `fk_APARTAMENTO_PROPRIETARIO1_idx` (`ID_PROPRIETARIO` ASC),
  CONSTRAINT `fk_Apartamento_Bloco1`
    FOREIGN KEY (`ID_BLOCO`)
    REFERENCES `SAFE_GATE`.`BLOCO` (`ID_BLOCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APARTAMENTO_PROPRIETARIO1`
    FOREIGN KEY (`ID_PROPRIETARIO`)
    REFERENCES `SAFE_GATE`.`PROPRIETARIO` (`ID_PROPRIETARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`MORADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`MORADOR` (
  `ID_MORADOR` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `ID_APARTAMENTO` INT NOT NULL,
  `FOTO` LONGBLOB NULL,
  PRIMARY KEY (`ID_MORADOR`),
  INDEX `fk_MORADOR_APARTAMENTO1_idx` (`ID_APARTAMENTO` ASC),
  CONSTRAINT `fk_MORADOR_APARTAMENTO1`
    FOREIGN KEY (`ID_APARTAMENTO`)
    REFERENCES `SAFE_GATE`.`APARTAMENTO` (`ID_APARTAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`VISITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`VISITA` (
  `ID_VISITA` INT NOT NULL AUTO_INCREMENT,
  `HORARIO` TIMESTAMP(2) NOT NULL,
  `FOTO` VARCHAR(45) NOT NULL,
  `ID_FUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`ID_VISITA`),
  INDEX `fk_VISITA_FUNCIONARIO1_idx` (`ID_FUNCIONARIO` ASC),
  CONSTRAINT `fk_VISITA_FUNCIONARIO1`
    FOREIGN KEY (`ID_FUNCIONARIO`)
    REFERENCES `SAFE_GATE`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`VEICULO` (
  `ID_VEICULO` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(45) NULL,
  `MARCA` VARCHAR(45) NULL,
  `MODELO` VARCHAR(45) NULL,
  `PLACA` VARCHAR(45) NOT NULL,
  `ID_MORADOR` INT NOT NULL,
  `ID_VISITA` INT NOT NULL,
  PRIMARY KEY (`ID_VEICULO`),
  INDEX `fk_VEICULO_MORADOR1_idx` (`ID_MORADOR` ASC),
  INDEX `fk_VEICULO_VISITA1_idx` (`ID_VISITA` ASC),
  CONSTRAINT `fk_VEICULO_MORADOR1`
    FOREIGN KEY (`ID_MORADOR`)
    REFERENCES `SAFE_GATE`.`MORADOR` (`ID_MORADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_VISITA1`
    FOREIGN KEY (`ID_VISITA`)
    REFERENCES `SAFE_GATE`.`VISITA` (`ID_VISITA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`VISITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`VISITANTE` (
  `ID_VISITANTE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `FOTO` LONGBLOB NULL,
  PRIMARY KEY (`ID_VISITANTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAFE_GATE`.`VISITA_HAS_VISITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAFE_GATE`.`VISITA_HAS_VISITANTE` (
  `ID_VISITA` INT NOT NULL,
  `ID_VISITANTE` INT NOT NULL,
  PRIMARY KEY (`ID_VISITA`, `ID_VISITANTE`),
  INDEX `fk_VISITA_has_VISITANTE_VISITANTE1_idx` (`ID_VISITANTE` ASC),
  INDEX `fk_VISITA_has_VISITANTE_VISITA1_idx` (`ID_VISITA` ASC),
  CONSTRAINT `fk_VISITA_has_VISITANTE_VISITA1`
    FOREIGN KEY (`ID_VISITA`)
    REFERENCES `SAFE_GATE`.`VISITA` (`ID_VISITA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VISITA_has_VISITANTE_VISITANTE1`
    FOREIGN KEY (`ID_VISITANTE`)
    REFERENCES `SAFE_GATE`.`VISITANTE` (`ID_VISITANTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
